apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nc5i
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-nc5i@sha256:3170e86f34ace3c50d9ef94d328d179c6052cffd407885137900bd9e0977e383
        name: my-nodejs
        resources: {}
status: {}
